// Rebuilds the two faces the viewer draws with, and the coverage table that
// decides between them.
//
// Run from this directory:
//
//     npm install subset-font fontkit
//     curl -L -o Outfit.ttf \
//       'https://raw.githubusercontent.com/google/fonts/main/ofl/outfit/Outfit%5Bwght%5D.ttf'
//     curl -L -o Manrope.ttf \
//       'https://raw.githubusercontent.com/google/fonts/main/ofl/manrope/Manrope%5Bwght%5D.ttf'
//     node subset.mjs
//
// Outfit and Manrope are the two faces the web UI already ships: `style.css`
// declares both under `font-family: "Outfit"`, Outfit for the Latin ranges and
// Manrope for `U+0400-045F`. The viewer uses the same pair for the same reason,
// so a name reads the same over the pitch as it does on the squad page.
//
// Both are pinned to `wght` 400, which is what `body` renders at.

import fs from 'node:fs';
import subsetFont from 'subset-font';
import { create as openFont } from 'fontkit';

const expand = (ranges) => {
  let text = '';
  for (const [lo, hi] of ranges) for (let cp = lo; cp <= hi; cp++) text += String.fromCodePoint(cp);
  return text;
};

// What a squad list is made of. Latin-1 and Latin Extended-A carry the bulk of
// it — é í á ć š ñ ő — and Extended-B the Romanian ș ț and Croatian đ.
const LATIN = [
  [0x0020, 0x007e], // Basic Latin
  [0x00a0, 0x00ff], // Latin-1 Supplement
  [0x0100, 0x017f], // Latin Extended-A
  [0x0180, 0x024f], // Latin Extended-B
  [0x0259, 0x0259], // ə — Azerbaijani schwa
  [0x0300, 0x036f], // combining marks, for names stored decomposed
  [0x2010, 0x2015], // hyphens and dashes
  [0x2018, 0x201d], // curly quotes — the ’ in O’Brien
  [0x2026, 0x2026], // ellipsis
];

// Everything the fallback face is reached for on top of that: the Russian UI
// strings, and the stray Greek letters that turn up inside Latin names. It gets
// the Latin ranges too — a name that falls back has to be drawn whole, not just
// the character that pushed it over.
const WIDE = [...LATIN, [0x0386, 0x03ce], [0x0400, 0x045f], [0x0490, 0x0491], [0x04b0, 0x04b1], [0x04e6, 0x04e7], [0x2116, 0x2116]];

const cut = async (input, output, ranges) => {
  const source = fs.readFileSync(input);
  const subset = await subsetFont(source, expand(ranges), {
    targetFormat: 'truetype',
    variationAxes: { wght: 400 },
  });
  fs.writeFileSync(output, subset);
  console.log(`${input} ${source.length} B -> ${output} ${subset.length} B`);
  return subset;
};

const outfit = await cut('Outfit.ttf', 'Outfit-subset.ttf', LATIN);
await cut('Manrope.ttf', 'Manrope-subset.ttf', WIDE);

// Outfit is missing 29 characters scattered through Latin Extended-A, so which
// face a label needs cannot be guessed from its script — it has to be read off
// the font. Collapse the subset's character set into ranges and hand them to
// `Typeface`, which is the only thing that decides between the two.
const covered = [...openFont(outfit).characterSet].sort((a, b) => a - b);
const ranges = [];
for (const cp of covered) {
  const last = ranges[ranges.length - 1];
  if (last && cp === last[1] + 1) last[1] = cp;
  else ranges.push([cp, cp]);
}
const rows = ranges.map(([lo, hi]) => `    (0x${lo.toString(16)}, 0x${hi.toString(16)}),`).join('\n');
fs.writeFileSync('coverage.rs', `// @generated by fonts/subset.mjs — do not edit.
//
// The characters \`Outfit-subset.ttf\` has glyphs for, as inclusive ranges,
// sorted and coalesced. \`Typeface::face_for\` reads this to decide whether a
// label can be drawn in Outfit or has to fall back to Manrope.

const OUTFIT_COVERAGE: &[(u32, u32)] = &[
${rows}
];
`);
console.log(`coverage.rs: ${covered.length} characters in ${ranges.length} ranges`);
