//! The twenty approved fields, initialized entirely at compile time.
//! Keep IDs and ordering stable: saved team assignments refer to these numbers.
use super::{Pattern, Style};

pub(super) static STYLES: [Style; 20] = [
    Style {
        id: 1,
        #[cfg(test)]
        name: "Classic emerald",
        pattern: Pattern::Transverse,
        bands: 14,
        albedo: [0.125, 0.245, 0.135],
        contrast: 0.85,
        wear: 0.45,
        variation: 0.70,
        grain_scale: 1.0,
        seed: 101,
    },
    Style {
        id: 2,
        #[cfg(test)]
        name: "Broad forest",
        pattern: Pattern::Transverse,
        bands: 10,
        albedo: [0.115, 0.205, 0.140],
        contrast: 1.05,
        wear: 0.50,
        variation: 0.65,
        grain_scale: 1.0,
        seed: 203,
    },
    Style {
        id: 3,
        #[cfg(test)]
        name: "Fine spring",
        pattern: Pattern::Transverse,
        bands: 22,
        albedo: [0.170, 0.275, 0.125],
        contrast: 0.72,
        wear: 0.25,
        variation: 0.60,
        grain_scale: 0.85,
        seed: 307,
    },
    Style {
        id: 4,
        #[cfg(test)]
        name: "Soft sage",
        pattern: Pattern::Transverse,
        bands: 16,
        albedo: [0.170, 0.240, 0.175],
        contrast: 0.36,
        wear: 0.35,
        variation: 0.90,
        grain_scale: 0.9,
        seed: 409,
    },
    Style {
        id: 5,
        #[cfg(test)]
        name: "Broad olive",
        pattern: Pattern::Transverse,
        bands: 8,
        albedo: [0.185, 0.240, 0.115],
        contrast: 0.70,
        wear: 0.60,
        variation: 1.0,
        grain_scale: 1.05,
        seed: 503,
    },
    Style {
        id: 6,
        #[cfg(test)]
        name: "Jade ribbons",
        pattern: Pattern::Transverse,
        bands: 18,
        albedo: [0.105, 0.240, 0.170],
        contrast: 1.0,
        wear: 0.30,
        variation: 0.60,
        grain_scale: 0.85,
        seed: 607,
    },
    Style {
        id: 7,
        #[cfg(test)]
        name: "Long emerald",
        pattern: Pattern::Longitudinal,
        bands: 10,
        albedo: [0.125, 0.245, 0.135],
        contrast: 0.85,
        wear: 0.40,
        variation: 0.75,
        grain_scale: 1.0,
        seed: 709,
    },
    Style {
        id: 8,
        #[cfg(test)]
        name: "Long pine",
        pattern: Pattern::Longitudinal,
        bands: 8,
        albedo: [0.105, 0.195, 0.125],
        contrast: 0.70,
        wear: 0.45,
        variation: 0.70,
        grain_scale: 0.9,
        seed: 811,
    },
    Style {
        id: 9,
        #[cfg(test)]
        name: "Fine lime",
        pattern: Pattern::Longitudinal,
        bands: 18,
        albedo: [0.180, 0.265, 0.110],
        contrast: 0.55,
        wear: 0.25,
        variation: 0.65,
        grain_scale: 0.85,
        seed: 907,
    },
    Style {
        id: 10,
        #[cfg(test)]
        name: "Soft mint lanes",
        pattern: Pattern::Longitudinal,
        bands: 12,
        albedo: [0.150, 0.245, 0.170],
        contrast: 0.30,
        wear: 0.35,
        variation: 0.90,
        grain_scale: 1.0,
        seed: 1009,
    },
    Style {
        id: 11,
        #[cfg(test)]
        name: "Emerald velvet",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.110, 0.235, 0.125],
        contrast: 0.0,
        wear: 0.20,
        variation: 0.45,
        grain_scale: 0.8,
        seed: 1103,
    },
    Style {
        id: 12,
        #[cfg(test)]
        name: "Deep forest",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.105, 0.185, 0.120],
        contrast: 0.0,
        wear: 0.30,
        variation: 0.65,
        grain_scale: 0.9,
        seed: 1201,
    },
    Style {
        id: 13,
        #[cfg(test)]
        name: "Spring green",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.165, 0.265, 0.115],
        contrast: 0.0,
        wear: 0.25,
        variation: 0.65,
        grain_scale: 0.85,
        seed: 1301,
    },
    Style {
        id: 14,
        #[cfg(test)]
        name: "Cool bluegrass",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.110, 0.215, 0.175],
        contrast: 0.0,
        wear: 0.35,
        variation: 0.75,
        grain_scale: 0.95,
        seed: 1409,
    },
    Style {
        id: 15,
        #[cfg(test)]
        name: "Warm olive",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.180, 0.230, 0.105],
        contrast: 0.0,
        wear: 0.45,
        variation: 1.0,
        grain_scale: 1.05,
        seed: 1511,
    },
    Style {
        id: 16,
        #[cfg(test)]
        name: "Silver sage",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.165, 0.225, 0.165],
        contrast: 0.0,
        wear: 0.25,
        variation: 0.60,
        grain_scale: 0.9,
        seed: 1601,
    },
    Style {
        id: 17,
        #[cfg(test)]
        name: "Lush jade",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.100, 0.250, 0.155],
        contrast: 0.0,
        wear: 0.20,
        variation: 0.50,
        grain_scale: 0.8,
        seed: 1709,
    },
    Style {
        id: 18,
        #[cfg(test)]
        name: "Natural rye",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.145, 0.225, 0.110],
        contrast: 0.0,
        wear: 0.65,
        variation: 1.25,
        grain_scale: 1.1,
        seed: 1801,
    },
    Style {
        id: 19,
        #[cfg(test)]
        name: "Fresh meadow",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.185, 0.265, 0.145],
        contrast: 0.0,
        wear: 0.30,
        variation: 0.95,
        grain_scale: 1.0,
        seed: 1901,
    },
    Style {
        id: 20,
        #[cfg(test)]
        name: "Bottle green",
        pattern: Pattern::Plain,
        bands: 0,
        albedo: [0.095, 0.195, 0.150],
        contrast: 0.0,
        wear: 0.40,
        variation: 0.90,
        grain_scale: 0.85,
        seed: 2003,
    },
];
