//! Guards on the generated stylesheet bundle.
//!
//! `build.rs` concatenates and (in release) minifies the CSS. The
//! minifier is hand-rolled, so the artifact it produces is checked here
//! rather than trusted — a mangled value silently voids a whole
//! declaration, and the damage only shows in release builds.

#[cfg(test)]
mod tests {
    use crate::common::default_handler::Assets;

    const BUNDLE: &str = "static/css/styles.min.css";

    /// Reads the bundle the build script actually wrote.
    struct Bundle;

    impl Bundle {
        fn text() -> String {
            let file = Assets::get(BUNDLE).expect("styles.min.css is generated by build.rs");
            String::from_utf8(file.data.to_vec()).expect("stylesheet is UTF-8")
        }

        /// Every `calc(…)` span in the sheet, innermost parens included.
        fn calc_spans(css: &str) -> Vec<String> {
            let mut spans = Vec::new();
            let bytes: Vec<char> = css.chars().collect();
            let mut at = 0;

            while let Some(found) = css[at..].find("calc(") {
                let start = at + found;
                let head: usize = css[..start].chars().count() + "calc".chars().count();
                let mut depth = 0usize;
                let mut end = head;

                for (offset, ch) in bytes[head..].iter().enumerate() {
                    match ch {
                        '(' => depth += 1,
                        ')' => {
                            depth -= 1;
                            if depth == 0 {
                                end = head + offset;
                                break;
                            }
                        }
                        _ => {}
                    }
                }

                spans.push(bytes[head..=end].iter().collect());
                at = start + "calc(".len();
            }

            spans
        }
    }

    /// A binary `+` or `-` inside `calc()` needs whitespace on both
    /// sides. Space on one side only is what a whitespace-collapsing
    /// minifier produces, and it invalidates the entire declaration —
    /// `padding: calc(var(--pad) - 6px) …` silently became `padding: 0`
    /// in release builds and the newspaper lost every margin it had.
    #[test]
    fn the_bundle_has_no_lopsided_calc_operators() {
        let css = Bundle::text();
        let mut broken: Vec<String> = Vec::new();

        for span in Bundle::calc_spans(&css) {
            let chars: Vec<char> = span.chars().collect();
            for i in 1..chars.len().saturating_sub(1) {
                if chars[i] != '+' && chars[i] != '-' {
                    continue;
                }
                // `--custom-property`, not an operator.
                if chars[i] == '-' && (chars[i - 1] == '-' || chars[i + 1] == '-') {
                    continue;
                }
                // A leading `-` on an identifier, e.g. `var(-x)`.
                if chars[i - 1] == '(' || chars[i - 1] == ',' {
                    continue;
                }
                if chars[i + 1] == ' ' && chars[i - 1] != ' ' {
                    broken.push(span.clone());
                    break;
                }
            }
        }

        assert!(
            broken.is_empty(),
            "{} calc expression(s) lost the space before an operator: {:?}",
            broken.len(),
            broken
        );
    }

    /// The whole point of the bundle is that the page can reach it.
    #[test]
    fn the_bundle_carries_the_newspaper() {
        let css = Bundle::text();

        assert!(css.contains(".np-sheet"), "newspaper styles are missing");
        assert!(css.contains("--np-pad"), "newspaper tokens are missing");
    }
}
