//! Guards on the generated stylesheet bundle.
//!
//! `build.rs` concatenates and (in release) minifies the CSS. The
//! minifier is hand-rolled, so the artifact it produces is checked here
//! rather than trusted — a mangled value silently voids a whole
//! declaration, and the damage only shows in release builds.

#[cfg(test)]
mod tests {
    use crate::common::default_handler::Assets;

    const BUNDLE: &str = "static/css/styles.min.css";

    /// Reads the bundle the build script actually wrote.
    struct Bundle;

    impl Bundle {
        fn text() -> String {
            let file = Assets::get(BUNDLE).expect("styles.min.css is generated by build.rs");
            String::from_utf8(file.data.to_vec()).expect("stylesheet is UTF-8")
        }

        /// The sheet with `/* … */` stripped. Tests that look for a
        /// selector must not match the prose in a comment explaining
        /// that selector — and the dev bundle keeps comments while the
        /// release one drops them, so a test that skipped this would
        /// pass and fail depending on the profile.
        fn without_comments(css: &str) -> String {
            let mut out = String::with_capacity(css.len());
            let mut rest = css;

            while let Some(start) = rest.find("/*") {
                out.push_str(&rest[..start]);
                match rest[start..].find("*/") {
                    Some(end) => rest = &rest[start + end + 2..],
                    None => return out,
                }
            }
            out.push_str(rest);
            out
        }

        /// Every `calc(…)` span in the sheet, innermost parens included.
        fn calc_spans(css: &str) -> Vec<String> {
            let mut spans = Vec::new();
            let bytes: Vec<char> = css.chars().collect();
            let mut at = 0;

            while let Some(found) = css[at..].find("calc(") {
                let start = at + found;
                let head: usize = css[..start].chars().count() + "calc".chars().count();
                let mut depth = 0usize;
                let mut end = head;

                for (offset, ch) in bytes[head..].iter().enumerate() {
                    match ch {
                        '(' => depth += 1,
                        ')' => {
                            depth -= 1;
                            if depth == 0 {
                                end = head + offset;
                                break;
                            }
                        }
                        _ => {}
                    }
                }

                spans.push(bytes[head..=end].iter().collect());
                at = start + "calc(".len();
            }

            spans
        }
    }

    /// A binary `+` or `-` inside `calc()` needs whitespace on both
    /// sides. Space on one side only is what a whitespace-collapsing
    /// minifier produces, and it invalidates the entire declaration —
    /// `padding: calc(var(--pad) - 6px) …` silently became `padding: 0`
    /// in release builds and the newspaper lost every margin it had.
    #[test]
    fn the_bundle_has_no_lopsided_calc_operators() {
        let css = Bundle::text();
        let mut broken: Vec<String> = Vec::new();

        for span in Bundle::calc_spans(&css) {
            let chars: Vec<char> = span.chars().collect();
            for i in 1..chars.len().saturating_sub(1) {
                if chars[i] != '+' && chars[i] != '-' {
                    continue;
                }
                // `--custom-property`, not an operator.
                if chars[i] == '-' && (chars[i - 1] == '-' || chars[i + 1] == '-') {
                    continue;
                }
                // A leading `-` on an identifier, e.g. `var(-x)`.
                if chars[i - 1] == '(' || chars[i - 1] == ',' {
                    continue;
                }
                if chars[i + 1] == ' ' && chars[i - 1] != ' ' {
                    broken.push(span.clone());
                    break;
                }
            }
        }

        assert!(
            broken.is_empty(),
            "{} calc expression(s) lost the space before an operator: {:?}",
            broken.len(),
            broken
        );
    }

    /// The whole point of the bundle is that the page can reach it.
    #[test]
    fn the_bundle_carries_the_newspaper() {
        let css = Bundle::text();

        assert!(css.contains(".np-sheet"), "newspaper styles are missing");
        assert!(css.contains("--np-pad"), "newspaper tokens are missing");
    }

    /// The newspaper's column gutters — the hairline rules between the
    /// stories set side by side — are drawn by nth-child rules that a
    /// `:not()` lifts to (0,3,0). A media query adds nothing to
    /// specificity, so the narrow-screen blocks that clear those gutters
    /// have to carry a pseudo-class of their own to reach the same
    /// weight and win on source order. A plain `.np-run > .np-split`
    /// there is (0,2,0) and loses to the wide-screen rule however late
    /// it is set, which leaves a vertical rule down the middle of a
    /// page that has only one column left.
    #[test]
    fn the_newspaper_column_gutters_can_be_cleared_on_a_narrow_screen() {
        let css = Bundle::without_comments(&Bundle::text());
        let flat: String = css.chars().filter(|c| !c.is_whitespace()).collect();

        for reset in [
            ".np-splits>.np-split:nth-child(n)",
            ".np-run>.np-split:nth-child(n)",
        ] {
            assert!(
                flat.contains(reset),
                "`{}` is gone: the responsive reset can no longer out-rank the \
                 gutter rules it exists to undo",
                reset
            );
        }
    }

    /// A global `a:link, a:visited, a:hover, a:active { text-decoration:
    /// none !important }` sits near the top of the sheet. Its specificity
    /// is (0,1,1), so a bare `.np-story-link { … !important }` — (0,1,0) —
    /// loses to it and the newspaper's player links render as plain type.
    /// Both halves of the escape hatch have to survive edits: the rule
    /// must be anchored on `a…:link` to out-specify the reset, AND carry
    /// its own `!important` to answer it.
    #[test]
    fn a_newspaper_player_link_outranks_the_global_underline_reset() {
        let css = Bundle::without_comments(&Bundle::text());

        let anchored = css
            .find("a.np-story-link:link")
            .expect("the player-link rule must be anchored on `a…:link` to beat `a:link`");
        let body = css[anchored..]
            .split_once('}')
            .map(|(head, _)| head)
            .unwrap_or_default();
        let flat: String = body.chars().filter(|c| !c.is_whitespace()).collect();

        assert!(
            flat.contains("text-decoration:underline!important"),
            "the player link's underline is not marked important and the global \
             reset will swallow it: {}",
            body
        );
    }

    /// The same wall, hit by the rule that marks a name in the middle of
    /// a paragraph. That one cannot use `text-decoration` at all — the
    /// global reset would swallow it — so it draws its rule with a
    /// background gradient, exactly as the briefs column does. A
    /// "tidy-up" that swaps it back to `text-decoration: underline`
    /// leaves every club and player named in body copy silently
    /// unmarked.
    #[test]
    fn a_newspaper_prose_link_draws_its_rule_without_text_decoration() {
        let css = Bundle::without_comments(&Bundle::text());

        let anchored = css
            .find("a.np-prose-link:link")
            .expect("the in-copy link rule must be anchored on `a…:link`");
        let body = css[anchored..]
            .split_once('}')
            .map(|(head, _)| head)
            .unwrap_or_default();
        let flat: String = body.chars().filter(|c| !c.is_whitespace()).collect();

        assert!(
            flat.contains("background-image:linear-gradient"),
            "the in-copy link draws no rule at all: {}",
            body
        );
        assert!(
            !flat.contains("text-decoration:underline"),
            "the global reset out-specifies this and the rule will not render: {}",
            body
        );
    }

    /// A player's press page marks the passages about him, and the mark
    /// needs a margin to stand in. The rule that opens that margin scores
    /// (0,3,0) — exactly what the column gutters score — so it only wins
    /// on source order, and moving the marking block above the gutters
    /// (an "alphabetise the sheet" tidy-up would) puts a 3px pencil
    /// stroke straight through the first word of every marked story.
    #[test]
    fn the_newspaper_cutting_margin_is_set_after_the_gutters_it_outranks() {
        let css = Bundle::without_comments(&Bundle::text());
        let flat: String = css.chars().filter(|c| !c.is_whitespace()).collect();

        for (gutter, cutting) in [
            (
                ".np-splits>.np-split:nth-child(2n)",
                ".np-splits>.np-split.np-cut",
            ),
            (
                // Whitespace-stripped, so `3n + 1` reads `3n+1` here.
                ".np-run>.np-split:not(:nth-child(3n+1))",
                ".np-run>.np-split.np-cut",
            ),
        ] {
            let gutter_at = flat
                .find(gutter)
                .unwrap_or_else(|| panic!("`{}` is gone from the sheet", gutter));
            let cutting_at = flat
                .find(cutting)
                .unwrap_or_else(|| panic!("`{}` is gone from the sheet", cutting));

            assert!(
                cutting_at > gutter_at,
                "`{}` is set before `{}`: they carry the same specificity, so \
                 the gutter padding wins and the pencil stroke lands on the type",
                cutting,
                gutter
            );
        }
    }

    /// The masthead is the same wall from the other side. On a player's
    /// page the nameplate links to the club's own paper, and it must
    /// stay plain type: a rule under a masthead reads as a printing
    /// fault, not as a cross-reference. Two things can break it — the
    /// link picking up Bootstrap's colour, or somebody "fixing" the
    /// missing underline by borrowing `np-story-link`. This pins the
    /// first; `the_nameplate_opens_the_clubs_own_paper_without_an_underline`
    /// (player newspaper) pins the second.
    #[test]
    fn a_newspaper_masthead_link_never_draws_a_rule() {
        let css = Bundle::without_comments(&Bundle::text());

        let anchored = css
            .find("a.np-masthead-link:link")
            .expect("the masthead-link rule must be anchored on `a…:link`");
        let body = css[anchored..]
            .split_once('}')
            .map(|(head, _)| head)
            .unwrap_or_default();
        let flat: String = body.chars().filter(|c| !c.is_whitespace()).collect();

        assert!(
            flat.contains("text-decoration:none!important"),
            "the masthead link must state its lack of underline: {}",
            body
        );
        assert!(
            flat.contains("color:inherit!important"),
            "without this the nameplate takes Bootstrap's link colour on a \
             page whose whole design is one black plate: {}",
            body
        );
    }
}
