use match_viewer_build::MatchViewer;
use std::collections::hash_map::DefaultHasher;
use std::env;
use std::fs;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();

    MatchViewerAsset::build(Path::new(&manifest_dir), Path::new(&out_dir));

    let css_dir = Path::new(&manifest_dir)
        .join("assets")
        .join("static")
        .join("css");
    let output_file = Path::new(&manifest_dir)
        .join("assets")
        .join("static")
        .join("css")
        .join("styles.min.css");

    // Watch for changes in CSS directory (use absolute path)
    println!("cargo:rerun-if-changed={}", css_dir.display());
    // Also watch the build script itself
    println!(
        "cargo:rerun-if-changed={}",
        Path::new(&manifest_dir).join("build.rs").display()
    );

    // Check if minification is enabled (release builds or explicit feature)
    let minify = env::var("PROFILE").map(|p| p == "release").unwrap_or(false)
        || env::var("CARGO_FEATURE_MINIFY_CSS").is_ok();

    // Define CSS files to bundle (in order)
    // Note: flags.css is excluded as it's already minified and very large (2.7MB)
    let css_files = ["style.css", "images.css"];

    let mut combined_css = String::new();

    // Add a header comment
    combined_css.push_str("/* Combined and ");
    if minify {
        combined_css.push_str("minified ");
    }
    combined_css.push_str("CSS - Generated by build.rs */\n");

    for file_name in &css_files {
        let file_path = css_dir.join(file_name);

        if file_path.exists() {
            // Watch individual CSS files with absolute paths
            println!("cargo:rerun-if-changed={}", file_path.display());

            match fs::read_to_string(&file_path) {
                Ok(content) => {
                    // Add file separator comment (only in non-minified mode)
                    if !minify {
                        combined_css.push_str(&format!("\n/* === {} === */\n", file_name));
                    }

                    let processed = if minify {
                        minify_css(&content)
                    } else {
                        content
                    };

                    combined_css.push_str(&processed);
                    combined_css.push('\n');
                }
                Err(e) => {
                    println!("cargo:warning=Failed to read {}: {}", file_name, e);
                }
            }
        } else {
            println!("cargo:warning=CSS file not found: {}", file_path.display());
        }
    }

    // Write the combined CSS file
    if let Err(e) = fs::write(&output_file, &combined_css) {
        println!("cargo:warning=Failed to write combined CSS: {}", e);
    } else {
        println!(
            "cargo:info=Generated {} ({} bytes, minified: {})",
            output_file.display(),
            combined_css.len(),
            minify
        );
    }

    // Generate a hash of the CSS content to force recompilation when CSS changes
    // This is necessary because rust-embed embeds files at compile time
    let mut hasher = DefaultHasher::new();
    combined_css.hash(&mut hasher);
    let css_hash = hasher.finish();

    // Write a Rust file with the hash that can be included to force recompilation
    let css_version = format!("{:x}", css_hash);
    let short_version = &css_version[..8.min(css_version.len())];

    let hash_file = Path::new(&out_dir).join("css_hash.rs");
    let hash_content = format!(
        "// Auto-generated by build.rs - DO NOT EDIT\n\
         #[allow(dead_code)]\n\
         const CSS_BUILD_HASH: u64 = {};\n\
         #[allow(dead_code)]\n\
         pub const CSS_VERSION: &str = \"{}\";\n",
        css_hash, short_version
    );
    fs::write(&hash_file, hash_content).expect("Failed to write css_hash.rs");
}

/// Stages the Bevy replay viewer (`src/match`) into `assets/static/match/`,
/// where `rust-embed` picks it up along with every other static file.
///
/// Building it here rather than by hand is what keeps the viewer honest: the
/// wasm the server hands out is always the one built from the sources sitting
/// next to it, and there is no second command to remember. The recipe itself
/// lives in `match_viewer_build`, which the dev match harness uses too.
struct MatchViewerAsset;

impl MatchViewerAsset {
    fn build(manifest_dir: &Path, out_dir: &Path) {
        let crate_dir = manifest_dir
            .parent()
            .map(|parent| parent.join("match"))
            .unwrap_or_else(|| PathBuf::from("../match"));
        let assets_dir = manifest_dir.join("assets").join("static").join("match");

        MatchViewer::watch(&crate_dir);

        if !MatchViewer::skipped() {
            if let Err(reason) =
                MatchViewer::stage(&crate_dir, &out_dir.join("match-viewer"), &assets_dir)
            {
                println!("cargo:warning=match viewer not rebuilt: {}", reason);
            }
        }

        // Recorded so the page can tell the difference between "the viewer is
        // here" and "this build had no wasm toolchain", and can cache-bust the
        // module when it changes.
        let contents = format!(
            "// Auto-generated by build.rs - DO NOT EDIT\n\
             pub const MATCH_VIEWER_AVAILABLE: bool = {};\n\
             pub const MATCH_VIEWER_VERSION: &str = \"{}\";\n",
            MatchViewer::staged(&assets_dir),
            MatchViewer::version(&assets_dir),
        );
        fs::write(out_dir.join("match_viewer.rs"), contents)
            .expect("Failed to write match_viewer.rs");
    }
}

/// Simple CSS minification function
/// Removes comments, unnecessary whitespace, and newlines
fn minify_css(css: &str) -> String {
    let mut result = String::with_capacity(css.len());
    let mut chars = css.chars().peekable();
    let mut in_string = false;
    let mut string_char = '"';
    let mut last_char = ' ';
    // Parenthesis nesting. Inside `calc()` and friends a space is an
    // operator delimiter, not decoration: drop the one before the minus
    // in `calc(var(--x) - 6px)` and the expression becomes invalid, which
    // takes the whole declaration down with it. The bug only shows in
    // release builds, where this function runs.
    let mut depth: u32 = 0;

    while let Some(c) = chars.next() {
        // Handle string literals
        if !in_string && (c == '"' || c == '\'') {
            in_string = true;
            string_char = c;
            result.push(c);
            continue;
        }

        if in_string {
            result.push(c);
            if c == string_char && last_char != '\\' {
                in_string = false;
            }
            last_char = c;
            continue;
        }

        // Remove comments
        if c == '/' && chars.peek() == Some(&'*') {
            chars.next(); // consume '*'
            // Skip until */
            while let Some(cc) = chars.next() {
                if cc == '*' && chars.peek() == Some(&'/') {
                    chars.next(); // consume '/'
                    break;
                }
            }
            continue;
        }

        // Handle whitespace
        if c.is_whitespace() {
            // Inside a function, collapse runs but never delete them.
            if depth > 0 {
                while chars.peek().map(|c| c.is_whitespace()).unwrap_or(false) {
                    chars.next();
                }
                let next_closes = matches!(chars.peek(), Some(')') | Some(','));
                if last_char != '(' && last_char != ',' && !next_closes {
                    result.push(' ');
                    last_char = ' ';
                }
                continue;
            }

            // Collapse multiple whitespace to single space
            // Skip whitespace after certain characters
            // `)` deliberately absent: `rgba(…) inset` and
            // `calc(…) var(…)` both need the space that follows it.
            let skip_after = ['{', '}', ';', ':', ',', '>', '+', '~', '('];
            let skip_before = ['{', '}', ';', ':', ',', '>', '+', '~', '(', ')'];

            if !skip_after.contains(&last_char) {
                // Check if next non-whitespace needs space
                while chars.peek().map(|c| c.is_whitespace()).unwrap_or(false) {
                    chars.next();
                }

                if let Some(&next) = chars.peek() {
                    // A space between a bare word and `(` is load-bearing:
                    // `and (max-width: …)` minified to `and(max-width: …)`
                    // tokenises as a function, the media query stops
                    // parsing, and the whole block is dropped. Nothing
                    // else at this depth puts a space there, so keeping
                    // it costs one byte per media query.
                    let word_before_paren =
                        next == '(' && (last_char.is_ascii_alphanumeric() || last_char == '-');
                    if (!skip_before.contains(&next) || word_before_paren) && !result.is_empty() {
                        result.push(' ');
                        last_char = ' ';
                    }
                }
            } else {
                // Skip whitespace after special chars
                while chars.peek().map(|c| c.is_whitespace()).unwrap_or(false) {
                    chars.next();
                }
            }
            continue;
        }

        if c == '(' {
            depth += 1;
        } else if c == ')' {
            depth = depth.saturating_sub(1);
        }

        result.push(c);
        last_char = c;
    }

    // Additional cleanup passes
    let result = result
        .replace(" {", "{")
        .replace("{ ", "{")
        .replace(" }", "}")
        .replace("} ", "}")
        .replace(": ", ":")
        .replace(" :", ":")
        .replace("; ", ";")
        .replace(" ;", ";")
        .replace(", ", ",")
        .replace(" ,", ",")
        .replace("  ", " ");

    result.trim().to_string()
}
